### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by mbukosky** [tivac/falcor-experiment#2]
Hey,

I know this might be a little random, but I am trying to play around with your example and I am having trouble running you app. I am not sure if it is a npm/node version issue that is messing me up. I was wondering if you had any ideas.

I am currently on.

```
λ npm --version
3.3.11

λ node --version
v4.2.1
```

I am getting the following error. (note, `npm install` worked fine). It seems that the `css-modulesify` isn't building correctly, because I do not see an output folder.

```
λ npm run build                                                                                                                         

> falcor-experiment@1.0.0 build C:\git\falcor-experiment                                                                                
> node build/browserify.js                                                                                                              

fs.js:549                                                                                                                               
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);                                                          
                 ^                                                                                                                      

Error: ENOENT: no such file or directory, open 'C:\git\falcor-experiment\output\scripts.js'                                             
    at Error (native)                                                                                                                   
    at Object.fs.openSync (fs.js:549:18)                                                                                                
    at Object.fs.writeFileSync (fs.js:1161:15)                                                                                          
    at C:\git\falcor-experiment\build\browserify.js:17:19                                                                               
    at C:\git\falcor-experiment\node_modules\browserify\index.js:774:13                                                                 
    at ConcatStream.<anonymous> (C:\git\falcor-experiment\node_modules\concat-stream\index.js:36:43)                                    
    at emitNone (events.js:72:20)                                                                                                       
    at ConcatStream.emit (events.js:166:7)                                                                                              
    at finishMaybe (C:\git\falcor-experiment\node_modules\readable-stream\lib\_stream_writable.js:509:14)                               
    at endWritable (C:\git\falcor-experiment\node_modules\readable-stream\lib\_stream_writable.js:519:3)                                
    at ConcatStream.Writable.end (C:\git\falcor-experiment\node_modules\readable-stream\lib\_stream_writable.js:484:5)                  

npm ERR! Windows_NT 6.1.7601                                                                                                            
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"       
npm ERR! node v4.2.1                                                                                                                    
npm ERR! npm  v3.3.11                                                                                                                   
npm ERR! code ELIFECYCLE                                                                                                                
npm ERR! falcor-experiment@1.0.0 build: `node build/browserify.js`                                                                      
npm ERR! Exit status 1                                                                                                                  
npm ERR!                                                                                                                                
npm ERR! Failed at the falcor-experiment@1.0.0 build script 'node build/browserify.js'.                                                 
npm ERR! Make sure you have the latest version of node.js and npm installed.                                                            
npm ERR! If you do, this is most likely a problem with the falcor-experiment package,                                                   
npm ERR! not with npm itself.                                                                                                           
npm ERR! Tell the author that this fails on your system:                                                                                
npm ERR!     node build/browserify.js                                                                                                   
npm ERR! You can get their info via:                                                                                                    
npm ERR!     npm owner ls falcor-experiment                                                                                             
npm ERR! There is likely additional logging output above.                                                                               

npm ERR! Please include the following file with any support request:                                                                    
npm ERR!     C:\git\falcor-experiment\npm-debug.log                                                                                     
```

**Comment by tivac** [comment]
You'll need to create an `/output` folder within the structure, sorry. I should stick an empty `.gitignore` in there so it's part of the repo but haven't gotten around to it.

**Comment by mbukosky** [comment]
Perfect! Thanks for all the help. I should have figured that one out.

**Comment by tivac** [comment]
:+1:
